version: 2
jobs:
  deploy-to-package-mamnagers:
    docker:
      - image: docker:stable-git
    working_directory: /root/project
    steps:
      - run:
          name: publish
          commnand: ./publish.sh

workflows:
  version: 2
  deploy-to-package-mamnagers:
    jobs:
    - deploy-to-package-mamnagers:
          filters:
            tags:
              only: /^.*/
            branches:
              ignore: /^.*/

